// const englishLetters = [
//     {letter: 'A', image: 'https://res.cloudinary.com/deypvyqod/image/upload/v1720400213/letters/%D8%AA%D9%81%D8%A7%D8%AD%D9%87_-_Copy_nnnlhj.jpg', number: 1},
//     {letter: 'B', image: 'banana.png', number: 2},
//     {letter: 'C', image: 'cat.png', number: 3},
//     {letter: 'D', image: 'dog.png', number: 4},
//     {letter: 'E', image: 'elephant.png', number: 5},
//     {letter: 'F', image: 'fish.png', number: 6},
//     {letter: 'G', image: 'grape.png', number: 7},
//     {letter: 'H', image: 'hat.png', number: 8},
//     {letter: 'I', image: 'icecream.png', number: 9},
//     {letter: 'J', image: 'jelly.png', number: 10},
//     {letter: 'K', image: 'kite.png', number: 11},
//     {letter: 'L', image: 'lion.png', number: 12},
//     {letter: 'M', image: 'monkey.png', number: 13},
//     {letter: 'N', image: 'nest.png', number: 14},
//     {letter: 'O', image: 'orange.png', number: 15},
//     {letter: 'P', image: 'pencil.png', number: 16},
//     {letter: 'Q', image: 'queen.png', number: 17},
//     {letter: 'R', image: 'rabbit.png', number: 18},
//     {letter: 'S', image: 'sun.png', number: 19},
//     {letter: 'T', image: 'tiger.png', number: 20},
//     {letter: 'U', image: 'umbrella.png', number: 21},
//     {letter: 'V', image: 'violin.png', number: 22},
//     {letter: 'W', image: 'whale.png', number: 23},
//     {letter: 'X', image: 'xylophone.png', number: 24},
//     {letter: 'Y', image: 'yacht.png', number: 25},
//     {letter: 'Z', image: 'zebra.png', number: 26},
//   ];
  